name: "Today I learned"
description: ""
author: "Tom Graham"

url: "http://tompedals.github.io"
baseurl: "/til"

twitter: tompedals
github: tompedals

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

permalink: pretty
highlighter: pygments

paginate: 50
paginate_path: "/page/:num"

exclude:
  - ".sass-cache"
  - "node_module"
  - "sass"
  - "Gemfile"
  - "Gemfile.lock"
  - "Gruntfile.js"
  - "package.json"

gems:
  - "jekyll-paginate"
